### ISSUE TITLE
Target host must not be null

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/mdba-hub#32]
Yesterday during the sprint review meeting there was a failure with the mdba hub. See below for the stacktrace from the catalina.out log file:

```
2016-03-23 04:45:07,282 ERROR [RestService]  Unable to obtain species details from BIE - Target host must not be null, or set in parameters.
java.lang.IllegalStateException: Target host must not be null, or set in parameters.
    at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:784)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:414)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:476)
    at groovyx.net.http.HTTPBuilder.post(HTTPBuilder.java:359)
    at groovyx.net.http.HTTPBuilder.post(HTTPBuilder.java:318)
    at au.org.ala.biocache.hubs.mdba.RestService.bulkLookupSpecies(RestService.groovy:143)
    at au.org.ala.biocache.hubs.mdba.RestService.getSpeciesListItemsForUid(RestService.groovy:91)
    at au.org.ala.biocache.hubs.mdba.BrowseByController.species(BrowseByController.groovy:35)
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:200)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by nickdos** [comment]
Closed with commit to ansible-inventories: https://github.com/AtlasOfLivingAustralia/ansible-inventories/commit/b87d0e44551c9755569a335657e5e2c8acc345fd
